class daneshjo:
    def _init_(name,family,nationalcode,coddaneshjoo,city,moadel):
        self.name = name
        self.family = family
        self. nationalcode = nationalcode
        self.coddaneshjoo = coddaneshjoo
        self.city = city
        self.moadel = moadel
daneshjo1 = daneshjo(pari,zarin,3920651219,1323302,karaj,19)

def daneshjo_class(self):
    if self.moadel > 17:
        print('momtaz')
    else:
        print('mamooli')
daneshjo_class(daneshjo1)